# Generated by Django 4.1.6 on 2023-02-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomeadmin", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=11)),
                ("tipo_acesso", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomecolaborador", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=11)),
                ("tipo_acesso", models.CharField(max_length=50)),
                ("equipe", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Lider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomelider", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=11)),
                ("tipo_acesso", models.CharField(max_length=50)),
                ("equipe", models.CharField(max_length=50)),
            ],
        ),
    ]
